chore: Bakend setup rework

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,3 +39,19 @@ jobs:
 
       - name: Run build
         run: npm run build
+
+      - name: Run the server
+        run: |
+          timeout 20s node ./build/main.js
+          exit_code=$? # Get the exit code of the previous command
+
+          if [ $exit_code -eq 124 ]; then
+            echo "Server started without errors"
+            exit 0
+          elif [ $exit_code -ne 0 ]; then
+            echo "Server encountered an error"
+            exit 1
+          else
+            echo "Server exited unexpectedly"
+            exit 1
+          fi
